os: osx
osx_image: xcode12.4
language: swift
xcodebuild clean build test -project FINCH.xcodeproj -scheme FINCH -sdk iphonesimulator -destination "platform=iOS Simulator,OS=14.4,name=iPhone 12" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO

